site_name: felbinger.eu
site_url: https://felbinger.eu/
copyright: >-
  Copyright &copy; 2020 - 2025 Nico Felbinger
  &nbsp; – &nbsp;
  <a href="/imprint.html">Imprint</a>
  &nbsp; – &nbsp;
  <a href="#__consent">Change cookie settings</a>

exclude_docs: |
  !.well-known
  !robots.txt

theme:
  name: 'material'
  # paths are relative to the docs folder
  logo: media/favicon-32x32.png
  favicon: media/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'green'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'green'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  language: en
  direction: ltr
  icon:
    repo: fontawesome/brands/github

  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
  - git-revision-date-localized:
      exclude:
        - blog/archive/*
        - blog/category/*
  - offline
  - privacy
  - search:
      lang: en
  - blog:
      blog_dir: blog
      archive: false
      categories: true

extra:
  generator: false  # remove footer: Made with Material for MkDocs
  consent:
    title: Cookie consent
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make my documentation better.
